### ISSUE TITLE
register_login_c.lua

### ISSUE THREAD

**Issue by z0ckyZockt97** [Noneatme/iLife-SA#3]
Warum ist der komplette Inhalt der register_login_c.lua ausgeklammert?

**Comment by Noneatme** [comment]
Das ist das alte, nicht mehr unterstützte Login GUI von Danny. Es wurde mit dem client/Guis/Util/cRegisterGUI.lua ausgetauscht und nicht mehr benötigt. Mit "nicht mehr benötigt" meine ich eigentlich es würde überhaupt nicht mehr funktionieren und funktioniert auch nicht.

Grüßle

**Comment by z0ckyZockt97** [comment]
Alles klar...
Dann weis ich bescheid ;)
